name: npm-publish

on:
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
      
jobs:
  build:
  
    name: npm-publish
    runs-on: ubuntu-latest
    
    permissions: 
      contents: read
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci --force
    
    - name: Build
      run: npx nx build --configuration=production

    - name: Test
      run: npx nx run-many --target=test --projects=share-buttons-demo --watch=false --browsers=ChromeHeadless
